### ISSUE TITLE
vagrant install npm syscall symlink errors for backend and backend-v1

### ISSUE THREAD

**Issue by ejacobhayes** [kumahq/kuma-demo#89]
**Describe the bug**
Vagrant had the following errors while building the backend and backend-v1 containers.

Errors:
   backend: ERR! syscall symlink
   backend: npm ERR! path ../mime/cli.js
   backend: npm ERR! dest /home/vagrant/kuma-demo/backend/node_modules/.bin/mime
   backend: npm ERR! errno -71
   backend: npm ERR! EPROTO: protocol error, symlink '../mime/cli.js' -> '/home/vagrant/kuma-demo/backend/node_modules/.bi

**To Reproduce**
1. Clone kuma-demo master branch
2. vagrant up

Fix: 
Update both files:
~/vagrant/backend/app/install.sh 
~/vagrant/backend-v1/app/install.sh

Change line from:
npm install

Change line to:
npm install  --no-bin-links

**Desktop (please complete the following information):**
 - OS: Windows 
 - Kuma: 0.7.1
 - Environment: Vagrant

**Comment by devadvocado** [comment]
Hey @ejacobhayes, having difficulty replicating the issue you've encountered. Several updates have been made to the demo repository since this issue was opened so perhaps one of the following changes addressed it. I'll close this for now and if you can replicate it again, reopen this and let's work on solving it.
